### PR TITLE
fix: docker-compose for superset

### PR DESCRIPTION
**Pull request by wey-gu**
docker-compose seems to be the default shell entry?

Great examples, Pat, thanks!

### CODE REVIEW

**Comment by pnadolny13** [comment]
@wey-gu thanks for the contribution! I'm going to merge it in.

Curious though, were you able to get these examples working? Any other helpful feedback 😄 ?

**Comment by wey-gu** [comment]
Dear @pnadolny13, it's actually quite smooth! And I had also seen a couple of videos from you on YouTube!
Thanks a lot!

I would like to create a reference data stack with metadata discovery and data lineage, where its base(databases, ETL) will be based on meltano as it's elegant, mature, and yet open-source.

I was about to create some bootstrap ETLs with meltano before seeing your repo, then I suddenly decided to refer to yours instead of recreating one, thanks so much!

**Comment by pnadolny13** [comment]
> Dear @pnadolny13, it's actually quite smooth! And I had also seen a couple of videos from you on YouTube! Thanks a lot!
> 
> I would like to create a reference data stack with metadata discovery and data lineage, where its base(databases, ETL) will be based on meltano as it's elegant, mature, and yet open-source.
> 
> I was about to create some bootstrap ETLs with meltano before seeing your repo, then I suddenly decided to refer to yours instead of recreating one, thanks so much!

@wey-gu awesome, great to hear it worked for you!

That sounds like a cool project. If you're interested, once you've got something working, you can come join us in Meltano community demo day to show what you built!

cc @ tayloramurphy

**Comment by wey-gu** [comment]
> > Dear @pnadolny13, it's actually quite smooth! And I had also seen a couple of videos from you on YouTube! Thanks a lot!
> > I would like to create a reference data stack with metadata discovery and data lineage, where its base(databases, ETL) will be based on meltano as it's elegant, mature, and yet open-source.
> > I was about to create some bootstrap ETLs with meltano before seeing your repo, then I suddenly decided to refer to yours instead of recreating one, thanks so much!
> 
> @wey-gu awesome, great to hear it worked for you!
> 
> That sounds like a cool project. If you're interested, once you've got something working, you can come join us in Meltano community demo day to show what you built!
> 
> cc @ tayloramurphy

That'll be great, not sure if it's worthy to be demonstrated, while I'd love to share it on the demo day, it's WIP here https://github.com/wey-gu/data-lineage-ref-solution btw.

Thanks!

**Pull request merged**
